import { Template, Preset, Settings } from '@/utils/defines';
import { DEFAULT_DEPTH, DEFAULT_WEIGHT } from '@st/scripts/world-info.js';

export const defaultTemplate: Template = {
    decorator: '@@record',
    tag: '',
    prompts: [
        {
            name: 'Character Note',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'charNote',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Author\'s Note',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'authorsNote',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'World info Depth 4',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'worldInfoDepth4',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Prompt Depth 4',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: false,
            internal: 'presetDepth4',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'World info Depth 3',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'worldInfoDepth3',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Prompt Depth 3',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: false,
            internal: 'presetDepth3',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'World info Depth 2',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'worldInfoDepth2',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Prompt Depth 2',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: false,
            internal: 'presetDepth2',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'World info Depth 1',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'worldInfoDepth1',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Prompt Depth 1',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: false,
            internal: 'presetDepth1',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'World info Depth 0',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'worldInfoDepth0',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Prompt Depth 0',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: false,
            internal: 'presetDepth0',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Last User Message',
            role: 'user',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'lastUserMessage',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Last Character Message',
            role: 'assistant',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'lastCharMessage',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Instruction',
            role: 'user',
            triggers: [],
            prompt: 'Based on the above, update the following outdated information:\n\n{{original}}\n\nOutput only the updated content.',
            injectionPosition: 'relative',
            enabled: true,
            internal: null,
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        }
    ],
    regex: '',
    findRegex: '',
    filters: ['worldInfoDepth', 'authorsNoteDepth', 'charDepth', 'presetDepth'],
}

export const defaultPreset: Preset = {
    name: 'Default',
    prompts: [
        {
            name: 'Main Prompt',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'main',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'World Info (before)',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'worldInfoBefore',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Persona Description',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'personaDescription',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Char Description',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'charDescription',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Char Personality',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'charPersonality',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Scenario',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'scenario',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Enhance Definitions',
            role: 'system',
            triggers: [],
            prompt: 'If you have more knowledge of {{char}}, add to the character\'s lore and personality to enhance them but keep the Character Sheet\'s definitions absolute.',
            injectionPosition: 'relative',
            enabled: false,
            internal: null,
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Auxiliary Prompt',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: null,
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'World Info (after)',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'worldInfoAfter',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Chat Examples',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'chatExamples',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
        {
            name: 'Chat History',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: true,
            internal: 'chatHistory',
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 65535,
        },
        {
            name: 'Post-History Instructions (jailbreak)',
            role: 'system',
            triggers: [],
            prompt: '',
            injectionPosition: 'relative',
            enabled: false,
            internal: null,
            injectionDepth: DEFAULT_DEPTH,
            injectionOrder: DEFAULT_WEIGHT,
            maxDepth: 999,
        },
    ],
    regexs: [],
    templates: {
        "@@replace:": {
            "decorator": "@@replace",
            "tag": "",
            "prompts": [
                {
                    name: 'Character Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'charNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Author\'s Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'authorsNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    "name": "Last User Message",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{lastUserMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Last Character Message",
                    "role": "assistant",
                    "triggers": [],
                    "prompt": "{{lastCharMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Instruction",
                    "role": "user",
                    "triggers": [],
                    "prompt": "Based on the above, update the following document:\n<doc>\n{{current}}\n</doc>\n\nOutput only the updated document content, and it must be wrapped in `<doc>` tags.\nFor example:\n<doc>\nLatest document content\n</doc>\n\n\nIf no update is needed, output the original content as is.",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                }
            ],
            "regex": "/<doc>([\\s\\S]+?)<\\/doc>/i",
            "findRegex": "",
            "filters": [
                "worldInfoDepth",
                "authorsNoteDepth",
                "presetDepth",
                "charDepth"
            ],
            "retryCount": 3,
            "retryInterval": 1000,
        },
        "@@replace_diff:": {
            "decorator": "@@replace_diff",
            "tag": "",
            "prompts": [
                {
                    name: 'Character Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'charNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Author\'s Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'authorsNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    "name": "Last User Message",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{lastUserMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Last Character Message",
                    "role": "assistant",
                    "triggers": [],
                    "prompt": "{{lastCharMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Instruction",
                    "role": "user",
                    "triggers": [],
                    "prompt": "Based on the content above, update the following document:\n<doc>\n{{current}}\n</doc>\n\nThe `<doc>` tags serve only to mark the beginning and end of the document; they are not part of the document itself and should not be used for patch positioning.\nGenerate the diff patch using the `git diff -u` (Unified Diff) format, and enclose it within `<diff>` tags.\nLine numbers should be calculated relative to the line immediately following `<doc>` as 0, and the line immediately preceding `</doc>` as EOF.\nUse `text.txt` as the filename.\n\nFor example:\n<diff>\n--- a/text.txt\n+++ b/text.txt\n@@ -1,3 +1,3 @@\nHello\n-World\n+World!\nHow are you?\n</diff>\n\nIf no updates are required, output an empty patch.",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                }
            ],
            "regex": "/<diff>([\\s\\S]*?)<\\/diff>/",
            "findRegex": "",
            "filters": [
                "worldInfoDepth",
                "authorsNoteDepth",
                "presetDepth",
                "charDepth"
            ],
            "retryCount": 3,
            "retryInterval": 1000,
        },
        "@@replace_search:": {
            "decorator": "@@replace_search",
            "tag": "",
            "prompts": [
                {
                    name: 'Character Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'charNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Author\'s Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'authorsNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    "name": "Last User Message",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{lastUserMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Last Character Message",
                    "role": "assistant",
                    "triggers": [],
                    "prompt": "{{lastCharMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Instruction",
                    "role": "user",
                    "triggers": [],
                    "prompt": "Based on the above, update the following document:\n<doc>\n{{current}}\n</doc>\n\nThe `<doc>` tag is solely used to mark the beginning and end of the document; it is not part of the document content itself.\nOutput the modified document content using Git conflict syntax, enclosed within `<edit>` tags.\nMultiple Git conflict blocks are permitted, and the content may include line breaks.\n\nFor example:\n<edit>\n<<<<<<< SEARCH\nold content 1\n=======\nnew content 1\n>>>>>>> REPLACE\n<<<<<<< SEARCH\nold content 2\n=======\nnew content 2\n>>>>>>> REPLACE\n</edit>\n\nIf no updates are required, output an empty `<edit>` tag.",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                }
            ],
            "regex": "/<edit>([\\s\\S]*?)<\\/edit>/i",
            "findRegex": "",
            "filters": [
                "worldInfoDepth",
                "authorsNoteDepth",
                "presetDepth",
                "charDepth"
            ],
            "retryCount": 3,
            "retryInterval": 1000,
        },
        "@@variables_json:": {
            "decorator": "@@variables_json",
            "tag": "",
            "prompts": [
                {
                    name: 'Character Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'charNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Author\'s Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'authorsNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    "name": "Last User Message",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{lastUserMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Last Character Message",
                    "role": "assistant",
                    "triggers": [],
                    "prompt": "{{lastCharMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Instruction",
                    "role": "user",
                    "triggers": [],
                    "prompt": "Update the following JSON document based on the content above:\n<json>\n{{current}}\n</json>\n\nThe `<json>` tags serve only to delimit the start and end of the document and are not part of the document itself.\nOutput a patch in accordance with the `RFC 7396: JSON Merge Patch` standard to update the JSON document, enclosed within `<json>` tags.\n\nFor example:\n<json>\n{ \"a\": 1, \"b\": { \"c\": 2 } }\n</json>\n\nIf no updates are required, output an empty JSON object.",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                }
            ],
            "regex": "/<json>([\\s\\S]*?)<\\/json>/i",
            "findRegex": "",
            "filters": [
                "worldInfoDepth",
                "authorsNoteDepth",
                "presetDepth",
                "charDepth"
            ],
            "retryCount": 3,
            "retryInterval": 1000,
        },
        "@@variables_yaml:": {
            "decorator": "@@variables_yaml",
            "tag": "",
            "prompts": [
                {
                    name: 'Character Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'charNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Author\'s Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'authorsNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    "name": "Last User Message",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{lastUserMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Last Character Message",
                    "role": "assistant",
                    "triggers": [],
                    "prompt": "{{lastCharMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Instruction",
                    "role": "user",
                    "triggers": [],
                    "prompt": "Based on the above content, update the following YAML document:\n<yaml>\n{{current}}\n</yaml>\n\nThe `<yaml>` tags serve only to delimit the start and end of the document and are not part of the document itself.\nOutput the content of the fields requiring updates; the updates will be applied in a format similar to `RFC 7396: JSON Merge Patch`, enclosed within `<yaml>` tags.\n\nFor example:\n<yaml>\na: 1\nb:\n  c: 2\n</yaml>\n\nIf no updates are required, output an empty YAML document.",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                }
            ],
            "regex": "/<yaml>([\\s\\S]*?)<\\/yaml>/i",
            "findRegex": "",
            "filters": [
                "worldInfoDepth",
                "authorsNoteDepth",
                "presetDepth",
                "charDepth"
            ],
            "retryCount": 3,
            "retryInterval": 1000,
        },
        "@@variables_jsonpatch:": {
            "decorator": "@@variables_jsonpatch",
            "tag": "",
            "prompts": [
                {
                    name: 'Character Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'charNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Author\'s Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'authorsNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    "name": "Last User Message",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{lastUserMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Last Character Message",
                    "role": "assistant",
                    "triggers": [],
                    "prompt": "{{lastCharMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Instruction",
                    "role": "user",
                    "triggers": [],
                    "prompt": "Update the following JSON document based on the content above:\n<json>\n{{current}}\n</json>\n\nThe `<json>` tags serve only to delimit the start and end of the document and are not part of the document itself.\nOutput the update patch in the format of `RFC 6902: JSON Patch`, wrapping the output content within `<patch>` tags.\n\nFor example:\n<patch>\n[\n  { \"op\": \"replace\", \"path\": \"/a/b/c\", \"value\": 42 },\n  { \"op\": \"add\", \"path\": \"/d/e/f\", \"value\": [ \"foo\", \"bar\" ] },\n  { \"op\": \"replace\", \"path\": \"/g/h/i\", \"value\": 42 }\n]\n</patch>\n\nIf no updates are required, output an empty JSON object.",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                }
            ],
            "regex": "",
            "findRegex": "",
            "filters": [
                "worldInfoDepth",
                "authorsNoteDepth",
                "presetDepth",
                "charDepth"
            ],
            "retryCount": 3,
            "retryInterval": 1000,
        },
        "@@evaluate_ejs:": {
            "decorator": "@@evaluate_ejs",
            "tag": "",
            "prompts": [
                {
                    name: 'Character Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'charNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Author\'s Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'authorsNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    "name": "Last User Message",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{lastUserMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Last Character Message",
                    "role": "assistant",
                    "triggers": [],
                    "prompt": "{{lastCharMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Instruction",
                    "role": "user",
                    "triggers": [],
                    "prompt": "Based on the information provided above and the following requirements, generate EJS code:\n\n{{original}}\n\nThe output EJS code must be wrapped within an outermost `<ejs>` tag, with code blocks enclosed using `<%% ... %%>` internally.\n\nFor example:\n<ejs>\n<%% setvar('stat_data.var1', 1) %%>\n</ejs>\n\nIf the code cannot be generated, output an empty `<ejs>` block.",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                }
            ],
            "regex": "/<ejs>([\\s\\S]*?)<\\/ejs>/i",
            "findRegex": "",
            "filters": [
                "worldInfoDepth",
                "authorsNoteDepth",
                "presetDepth",
                "charDepth"
            ],
            "retryCount": 3,
            "retryInterval": 1000,
        },
        "@@replace_ejs:": {
            "decorator": "@@replace_ejs",
            "tag": "",
            "prompts": [
                {
                    name: 'Character Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'charNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Author\'s Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'authorsNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    "name": "Last User Message",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{lastUserMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Last Character Message",
                    "role": "assistant",
                    "triggers": [],
                    "prompt": "{{lastCharMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Instruction",
                    "role": "user",
                    "triggers": [],
                    "prompt": "Based on the information provided above and the following requirements, generate EJS code:\n\n{{original}}\n\nThe output EJS code must be wrapped within an outermost `<ejs>` tag, with code blocks enclosed using `<%% ... %%>` internally.\n\nFor example:\n<ejs>\n<%% setvar('stat_data.var1', 1) %%>\n</ejs>\n\nIf the code cannot be generated, output an empty `<ejs>` block.",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                }
            ],
            "regex": "",
            "findRegex": "",
            "filters": [
                "worldInfoDepth",
                "authorsNoteDepth",
                "presetDepth",
                "charDepth"
            ],
            "retryCount": 3,
            "retryInterval": 1000,
        },
        "@@append_output:": {
            "decorator": "@@append_output",
            "tag": "",
            "prompts": [
                {
                    name: 'Character Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'charNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Author\'s Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'authorsNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    "name": "Last User Message",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{lastUserMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Last Character Message",
                    "role": "assistant",
                    "triggers": [],
                    "prompt": "{{lastCharMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Instruction",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{original}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                }
            ],
            "regex": "",
            "findRegex": "",
            "filters": [
                "worldInfoDepth",
                "authorsNoteDepth",
                "presetDepth",
                "charDepth"
            ],
            "retryCount": 3,
            "retryInterval": 1000,
        },
        "@@append_output_ejs:": {
            "decorator": "@@append_output_ejs",
            "tag": "",
            "prompts": [
                {
                    name: 'Character Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'charNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Author\'s Note',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'authorsNote',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 4',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth4',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 3',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth3',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 2',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth2',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 1',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth1',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'World info Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: true,
                    internal: 'worldInfoDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    name: 'Prompt Depth 0',
                    role: 'system',
                    triggers: [],
                    prompt: '',
                    injectionPosition: 'relative',
                    enabled: false,
                    internal: 'presetDepth0',
                    injectionDepth: DEFAULT_DEPTH,
                    injectionOrder: DEFAULT_WEIGHT,
                    maxDepth: 999,
                },
                {
                    "name": "Last User Message",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{lastUserMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Last Character Message",
                    "role": "assistant",
                    "triggers": [],
                    "prompt": "{{lastCharMessage}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                },
                {
                    "name": "Instruction",
                    "role": "user",
                    "triggers": [],
                    "prompt": "{{original}}",
                    "injectionPosition": "relative",
                    "enabled": true,
                    "internal": null,
                    "injectionDepth": 4,
                    "injectionOrder": 100,
                    "maxDepth": 999
                }
            ],
            "regex": "",
            "findRegex": "",
            "filters": [
                "worldInfoDepth",
                "authorsNoteDepth",
                "presetDepth",
                "charDepth"
            ],
            "retryCount": 3,
            "retryInterval": 1000,
        },
    },
};

export const defaultSettings: Settings = {
    baseUrl: 'http://localhost:8080/v1',
    apiKey: '',
    model: 'None',
    contextSize: 8192,
    maxTokens: 4096,
    temperature: 1,
    topK: 1,
    topP: 1,
    presencePenalty: 0,
    frequencyPenalty: 0,
    promptPostProcessing: 'none',
    presets: {
        [defaultPreset.name]: defaultPreset,
    },
    currentPreset: defaultPreset.name,
    stream: false,
    includeHeaders: {},
    includeBody: {},
    excludeBody: {},
};